[package]
name = "proxy-address-blocker"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
eframe =  { version = "0.21", features = ["persistence"] }
egui_extras = { version = "0.21", features = ["svg", "image"] }
image = { version = "0.24", default-features = false, features = ["png"]}
hyper = { version = "0.14", features = ["full"] }
tokio = { version = "1.26", features = ["full"] }
csv = "1.2"
serde = { version = "1", features = ["derive"] }
colored = "2.0.0"
rfd = "0.11"